name: build documentation from adocs

on:
  push:
    branches:
    - main
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Asciidoctoring the docs to pretty HTML!
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get build container
      id: adocbuild-html
      uses: tonynv/asciidoctor-action@master
      with:
          program: "gem install asciidoctor-multipage && cd $GITHUB_WORKSPACE/docs && asciidoctor -r asciidoctor-multipage -b multipage_html5 -D html -a stylesheet=style.css -o index.html index.adoc"
    - name: Generate PDF
      id: adocbuild-pdf
      uses: tonynv/asciidoctor-action@master
      with:
          program: "gem install asciidoctor-multipage asciidoctor-diagram rouge text-hyphen && cd $GITHUB_WORKSPACE/docs && asciidoctor -r asciidoctor-pdf -b pdf -o document.pdf index.adoc"
    - name: Upload PDF 
        uses: actions/upload-artifact@v3
        with:
          name: PDF document
          path: document.pdf
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./docs/html
